# Generated by Django 5.2.3 on 2025-06-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=200)),
                ('type_commune', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('code_insee', models.CharField(blank=True, max_length=10)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('superficie_km2', models.FloatField(blank=True, null=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type_ville', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nom_ville'], name='api_commune_nom_vil_448d2a_idx'), models.Index(fields=['code_postal'], name='api_commune_code_po_6d596c_idx'), models.Index(fields=['departement'], name='api_commune_departe_ad7136_idx')],
                'unique_together': {('nom_ville', 'code_insee')},
            },
        ),
        migrations.CreateModel(
            name='JobOfferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=200)),
                ('job_offer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['departement'], name='api_joboffe_departe_415ab3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnemploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=200)),
                ('nbr_unemployed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['commune'], name='api_unemplo_commune_57511a_idx')],
            },
        ),
    ]
