services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: untec-backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    networks:
      - untec-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: untec-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - untec-network
    restart: unless-stopped

networks:
  untec-network:
    driver: bridge
